language: ruby
rvm:
- 2.2.0
env:
  global:
    - BMP_APIKEY=22da9e2e925b493823abbf5318aab45c
    - GMAP_APIKEY=AIzaSyCwlF6LxCOJOZyOLnaVZIQkQZshOY8XMBs
    - GITHUB_KEY=336e78e3b5ec2f903f69
    - GITHUB_SECRET=ba70e7c00318e6020163a8e311c8088875d87da1

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: DLp1GmTBsF1x4HR7eLCTTx+bLUSY1tbvDsZoAbGbyIIWtj8ZbnXtZw9MUnoXMkZ+biqbt2TP+9lVmCq3nu1UfA2DtZ+csYG9v5LY6hJKhI2phQyI5BJodyzSupttNiQWwEdtCrMUdjMN4MsixCU2vTpU48nPIt2vOrV+PgdKRLY=
  app: still-reef-5914
  run: "rake db:migrate"
